name: GentlemensDispute
version: 0.4
authors: [Malikk, Arzeyt]
main: us.twoguys.gentsdispute.GentlemensDispute
commands:
    duel:
        description: Challenges another player to a duel
        usage: /duel <player> [arena]
    challenge:
        description: Used to accept or decline a challenge
        aliases: ch
        usage: /challenge <accept or decline>
    ready:
        description: Must be entered by all participants for a match to begin
        usage: /ready
    select:
        description: Used to begin arena selection.
        usage: /select
    create:
        description: Used to create an arena based on the selected points
        usage: /create <arenaName>
    delete:
        description: Used to delete an arena
        usage: /delete <arenaName>
    listarenas:
        description: Displays a list of all arenas
        usage: /listarenas