name: GentlemensDispute
version: 0.5
authors: [Malikk, Arzeyt]
main: us.twoguys.gentsdispute.GentlemensDispute
commands:
    duel:
        description: Challenges another player to a duel
        usage: /duel <player> [arena] [wager amount]
    challenge:
        description: Used to accept or decline a challenge
        aliases: ch
        usage: /challenge <accept, decline, or raise> [raise amount]
    wager:
        description: Places wager on a match
        usage: /wager [Player] [wager amount]
    ready:
        description: Must be entered by all participants for a match to begin
        usage: /ready
    gdtp:
        description: Teleports players to and from arenas
        usage: /gdtp [arena]
    select:
        description: Used to begin arena selection.
        usage: /select
    create:
        description: Used to create an arena based on the selected points
        usage: /create <arenaName>
    delete:
        description: Used to delete an arena
        usage: /delete <arenaName>
    listarenas:
        description: Displays a list of all arenas
        usage: /listarenas
    visualize:
        description: Visualizes an arena
        usage: /visualize <arenaName>
softdepend: [Vault]